### ISSUE TITLE
Adding a new product problems

### ISSUE THREAD

**Issue by uskudarli** [penumbram/SWE573#21] opened 2016-05-29 18:29 UTC
I tried to add the following product:

Keci Peyniri
Bol protenli, cok lezzetli, nefis bir peynir. Peynirini biraz keskin sevenlere tavsiye edilir.
http://images.wisegeek.com/chevre-goat-cheese.jpg
price: 22
Quantity: _What is this for?_
**_No location: MISSING_** 
Sell Unit: By Kg
Producer: Lianna Tamer

The producer could not be selected and stayed empty.

I created this twice. The first time I did not see it in the list.
Second time, I saw it. But I don't know if this is the first or second one I added.

As suspected there is no producer, since the drop down selection did not work.

The LOCATION missing is a 
![tolgacaner_productadd_failure](https://cloud.githubusercontent.com/assets/1347035/15635326/534019c0-25e4-11e6-949a-d38a7491c7aa.png)
 problem.

**Comment by penumbram-zz** [comment] 2016-05-29 20:45
Just sat this. Wİll attempt to fix it tomorrow.

**Comment by penumbram-zz** [comment] 2016-05-30 22:12
The mentioned bug is now fixed. Other problems arising when updating and removing products are also addressed.

The **No Location** problem was happening because the page wasn't descriptive enough. Now I added the Location, Farms Info, Company and Farms Info fields, which belong to the **Producer**, not the product. Therefore now when a producer is selected, his/her related properties are shown to be more clear. These properties are not editable as they belong to the producer.

The quantity was intended to show the available number of stocks in their designated unit e.g. _100_ KG cheese or _50_ jars of whey. 

You may check the live version and/or the repository for the latest version.

**Closed as completed by penumbram-zz** 2016-05-30 22:12 UTC
Labels: BUG
